### ISSUE TITLE
Clean up deprecated/outdated/unused modules and classes

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#115]
While going through code and issues related to the 1.0 version of the API, I found some top-level modules/classes in the openeo python client that do not seem to be used (anymore?). It think we should remove these to streamline the code structure.

Some examples:

- `openeo/service.py`, last edit 15 months ago by @bgoesswe , is an abstract base class, but my IDE can't find concrete subclasses
- `openeo/processgraph.py` and `openeo/rest/rest_processgraph.py`: last edit 15 months ago by @bgoesswe  (except for minor import tweak by myself), my editor can't find usage of these classes
- `openeo/error_summary.py`: is only used in openeo-python-driver and openeo-geopyspark-driver: I think this should be moved to openeo-python-driver
- `openeo/catalog.py` with class `EOProduct`: is abstract base class, but I can't find concrete usage of it, last edit oct 2017 by @jdries

**Comment by bgoesswe** [comment]
`openeo/processgraph.py`:
I think we can remove this, I just added them, because I felt like it is more compliant with the client development guidelines (back then). But I think a Python dictionary is good enough to represent a process graph. (maybe keeping [this API section](https://openeo.org/documentation/1.0/developers/api/reference.html#section/Processes/Defining-Processes) in mind).
`openeo/service.py`:
This was thought to be a class like jobs, but for services, so this might be interesting in the future (since it could handle [these endpoints](https://openeo.org/documentation/1.0/developers/api/reference.html#tag/Secondary-Services)), so if we want to return a list of Job objects with connection.list_jobs (#43), we could also do that for services. But having a separate class for that might be up for discussion.

**Comment by m-mohr** [comment]
Potential implementation for service.py is in PR #206

**Comment by soxofaan** [comment]
just removed some old proof of concept leftovers around file API. Implementation was 0.4-only, didn't work, and the interface was not ideal (returned http status codes instead of throwing python exceptions). Better just start over fresh when we need file API support (#122 )

**Comment by soxofaan** [comment]
I think it's time to close this ticket now, most outdated/unused modules are cleaned up now
