### ISSUE TITLE
Work on processes instead of process graphs

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-client#155]
As far as I understand the code, the Python client still seems to mostly work on "process graphs" instead of full processes, which means you'd just pass the "process_graph" part of a full process description to methods and from recent work I've seen it also seems that the JSON output doesn't contain the process metadata, if available. But at least the process graph should be wrapped with `{"process_graph": ...}`. Not working with the full process description makes portability of processes hard and I'd propose to change this.

**Comment by jdries** [comment]
Can you clarify with an example of what you would expect?
We use the client to communicate with validated backends, which seems to work. The fact that I didn't wrap the json was just me doing things manually, but obviously the client will do the right thing when sending a request to a backend.

**Comment by m-mohr** [comment]
Okay, if the JSON serializer outputs `{process_graph: ...nodes...}` and not just the nodes, than that was a mis-understanding from the recent changes in openeo-usecases.

What confused me was that the methods all have parameters like "process_graph=None" or so, and that sounds like me I'd need to pass just the nodes, not the whole process.

I thought I saw examples just passing nodes, but maybe I just stumbled across old examples? I can't even find it anymore... so maybe nevermind.

Examples for "just nodes": 
```
{
  "1": {
    "process_id": "example",
    "arguments": {}
  }
}
```

Example for a full process:
```
{
  "process_graph": {
    "1": {
      "process_id": "example",
      "arguments": {}
    }
  }
}
```

**Comment by jdries** [comment]
It's indeed the case that internally (between client classes) we could be passing just the nodes, and wrap them in a 'full process' when we send it. But that's more of an internal thing, we anyway try to avoid exposing the graphs themselves to the user.
I may want to add a method that does save a proper json for a given graph, would have helped me avoid confusion!

**Comment by soxofaan** [comment]
re: in https://github.com/Open-EO/openeo-web-editor/issues/271  @m-mohr  suggest to reopen this ticket

However I don't think it is useful to reopen this.
The python client internally works often with "process graphs" instead of "processes", but that is just an implementation detail, a regular user should not be confronted with that.

Legacy-wise there are a couple of `DataCube` methods that indeed allow the user to export a "process graph" instead of a "process", but these are already flagged as "not recommended to use" in the documentation, e.g.:
- https://open-eo.github.io/openeo-python-client/api.html?highlight=graph#openeo.rest.datacube.DataCube.graph
- https://open-eo.github.io/openeo-python-client/api.html?highlight=graph#openeo.rest.datacube.DataCube.flat_graph
The recommended way is using [`DataCube.to_json`](https://open-eo.github.io/openeo-python-client/api.html?highlight=graph#openeo.rest.datacube.DataCube.to_json)  which correctly exports a "process" with `{"process_graph": ...}` wrapper

I'm not sure what else there should be done here. Except maybe making the "not recommended to use" stronger in the docs. 
Throwing  warnings on usage or something like that is probably not a good idea because the methods are still being used internally.
