### ISSUE TITLE
support for ports not equal to 80 for development purposes?

### ISSUE THREAD

**Issue by kempenep** [Open-EO/openeo-python-client#166]
I tried to use the python client in a development environment by explicitly specifying the port 46204:
```
connection = openeo.connect("http://<internal>:46204")
```
where `<internal>` is an internal URL address

I get an error 
```
OpenEoApiError: [404] unknown: <html>
<head><title>CID Portal : Page not found</title></head>
```

When using an externally exposed address without specifying the port, all works fine.
It seems there is nothing wrong with the internal port, because I can access it both via the browser and python:
```
import requests
requests.get("http://openeo-dev.cidsn.jrc.it:46204")                   
<Response [200]>
```

Is it possible to explicitly set the port, or is only port 80 supported?

**Comment by jdries** [comment]
Hi Pieter,
hard to tell what the problem is, because openEO now uses a non trivial procedure to find the correct endpoint based on the .well-known/openeo path.
Could you enable more logging like this:

logging.basicConfig(level=logging.DEBUG)

This might give you the sequence of urls that the client is trying, which results in the issue. If it is the case that we would somehow drop the port number, it might also be easy to add back.

**Comment by kempenep** [comment]
Thanks for that suggestion, Jeroen. I have set the debug log level and noticed some of the GET capabilities have some hard coded links to the production endpoint. I will check if that will solve the issue.

**Comment by kempenep** [comment]
That was indeed the Issue. Thanks.
