### ISSUE TITLE
download_result: Expected one result file to download, but got 4

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-client#180]
It is a bit confusing that there are download_result and download_results. If using download_result it only loads a single file or gives an error if there are more. Can this be improved? At the very least I'd improve the error message, to "Expected one result file to download, but got 4 - please use download_results instead."

**Comment by soxofaan** [comment]
yeah, I also don't like that part of the python client, but it's left-over from the time when we assumed there was only one result file and now hard to get rid off without breaking existing code.

coincidentally I've been working on improving it yesterday, I hope I can finish it today

**Comment by m-mohr** [comment]
Great. There's also #179, which may improve the situation maybe a bit in Jupyter.

**Comment by soxofaan** [comment]
also related : #135

**Comment by soxofaan** [comment]
I added the documentation about this: https://open-eo.github.io/openeo-python-client/batch_jobs.html#download-batch-job-results

The recommended approach still has both  `download_files` and `download_file`, 
because we have too much legacy code (at VITO) using the "singular" version to just drop it unfortunately

The exception message should also be better now:

    openeo.rest.OpenEoClientException: 
    Can not use `download_file` with multiple assets. Use `download_files` instead

**Comment by soxofaan** [comment]
I'll close this ticket for now
