### ISSUE TITLE
UDF: rename function

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-client#27]
Rename the function for the udfs somehow that "udf" is mentioned (e.g. image.apply_tiles()), because otherwise it is hard to find the funtion that applies the udf.

**Comment by jdries** [comment]
In the current openEO process graphs. predefined functions and UDF's can often be used interchangeably (usually in a callback). In the python client, I usually indeed try to use apply_xxx to indicate that a function will be applied to something.

Otherwise I think we simply need to expand documentation. Closing for now, let me know if I still make a concrete change.
