### ISSUE TITLE
Shape of the Datacube

### ISSUE THREAD

**Issue by jsetty** [Open-EO/openeo-python-client#311]
Is it possible to know the shape of the cube before downloading?

**Comment by soxofaan** [comment]
In general not really because it's downloading that triggers the process graph execution.
It could be estimated somewhat based on spatial and temporal resolutions, but that would not be exact in a lot of cases I'm afraid.

Can you explain your use case a bit? Is it important to know the (exact or approximate) shape of your current cube before downloading, e.g. to do some additional downscaling?

**Comment by jsetty** [comment]
I was thinking of a use case where I want to use images from 2 different providers (Sentinel 1 and Sentinel 2). I would like to make sure they are of the same size. Is it a nice feature to request a cube of `t*param1*param2*d` size?

**Comment by soxofaan** [comment]
data source fusion is indeed possible (e.g. S1 and S2), what you typically have to do is resample e.g. the S1 data to the S2 grid and use `merge_cubes` to combine them in a single cube.

for example see the notebook https://github.com/Open-EO/openeo-python-client/blob/master/examples/notebooks/User-Workshop-2020-10/openeo-workshop-python-client.ipynb Section "Step 2. Merging Sentinel-1 Gamma0 (load_collection/resample_cube_spatial/merge_cubes)" .  This notebook might be a bit outdated, but it illustrates how to do data fusion
