### ISSUE TITLE
Adding possibiliy to visualize the process graph

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-python-client#34]
In the hackathon the idea came up to enable the users to visualize the process graph in a nice, like an actual image of an graph. 
Some tools were also mentioned to use it e.g.  [Tensor Board](https://github.com/tensorflow/tensorboard)
There is already a python package with a similiar solution in the [Dask package](http://dask.pydata.org/en/latest/graphviz.html)

**Comment by jdries** [comment]
This exists now: 
to_graphviz

**Comment by soxofaan** [comment]
example: 
![Screenshot from 2019-12-10 09-03-37](https://user-images.githubusercontent.com/44946/70507132-084d0e00-1b2c-11ea-9be7-c135fba489e7.png)

Note however that this requires the installation of an additional package `graphviz` (https://pypi.org/project/graphviz/). 
It is currently not listed as a dependency of the openeo client, because it is not vital and it is probably a hassle to get working on windows.
