### ISSUE TITLE
openeo.connect error instead of warning in newer version

### ISSUE THREAD

**Issue by theroggy** [Open-EO/openeo-python-client#387]
In newer versions of the client the warning has been changed to an error, so I'm not able to upgrade anymore.

I'm on a windows 10 system, and using this backend and authentication:
```
openeo.connect("https://openeo.vito.be").authenticate_oidc(provider_id="egi")
```
In older versions this gives this warning, in newer version an error:
```
File C:\Users\PIEROG\AppData\Roaming\openeo-python-client\refresh-tokens.json could be readable by others: mode 666 (expected: 600)
```

I tried all sorts of things by changing the access rights but I'm not able to get the mode to 600... the file always stays writable for "groups".
I also tried using setting it to 600 using the oschmod package, but this doesn't help either.

I'm working from a corporate network... maybe this is the problem?

Is there a possibility to bypass this check or another solution?

**Comment by JohanKJSchreurs** [comment]
> In newer versions of the client the warning has been changed to an error, so I'm not able to upgrade anymore.
> 
> I'm on a windows 10 system, and using this backend and authentication:
> 
> ```
> openeo.connect("https://openeo.vito.be").authenticate_oidc(provider_id="egi")
> ```
> 
> In older versions this gives this warning, in newer version an error:
> 
> ```
> File C:\Users\PIEROG\AppData\Roaming\openeo-python-client\refresh-tokens.json could be readable by others: mode 666 (expected: 600)
> ```
> 
> I tried all sorts of things by changing the access rights but I'm not able to get the mode to 600... the file always stays writable for "groups". I also tried using setting it to 600 using the oschmod package, but this doesn't help either.
> 
> I'm working from a corporate network... maybe this is the problem?
> 
> Is there a possibility to bypass this check or another solution?

Hi,
Thanks for letting us know about this error.

We tried to find a workaround that would help you get unstuck while we fix the issue in the software.
Unfortunately, we didn't find a quick workaround, so instead we are working on getting a fix out sooner.

Basically, we are going back to the previous behavior: logging a message instead of raising an error when there is a potential risk that the file is readable to others.

#### Temporary solution:

In the meantime, I think your best option is to stay on the older version for a little longer, until the version with the fix is released. Version 0.13 should work, that is the last version before this change was introduced.


#### Regarding the workarounds you tried and what you observed:

Indeed, it seems likely that some security policy on the corporate network would be what is preventing the Python client from setting stricter file access permissions on refresh-tokens.json.

Trying the oschmod command directly was indeed a logical choice, but the Python client also uses oschmod under the hood, so I’m afraid if it didn’t work in the client, then there is not much hope that using the oschmod command will fix the permissions.

#### Why we are reverting this change
 
We recently started using oschmod, hoping that it would give is enough compatibility between Windows and Linux so we could keep most of the current system for protecting the refresh-tokens.json file. But now that we have seen this type of problem, our conclusion is that the oschmod solution will not work very well for many Window users who work in environments with more complicated security rules.

Therefore, we will go back to letting the software log an info message, like before. Maybe we will find a better system for Windows in the future.

**Comment by theroggy** [comment]
OK, thanks!
