### ISSUE TITLE
CollectionMetadata ->  CubeMetadata?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#464]
https://github.com/Open-EO/openeo-python-client/blob/cbd40533d6158c0288d31bd66f35db62e1304aa9/openeo/metadata.py#L198-L200

"CollectionMetadata" got its name when data cubes where still called "ImageCollection" (instead of "DataCube"). But now that is getting a bit confusing: in openEO, "collections" is the source data one loads with `load_collection`, while "cubes" are the intermediate data structure one works with. So "CollectionMetadata" should better be called "CubeMetadata". 

Also, CollectionMetadata contains some specific dimension metadata parsing logic (cube:dimensions/eo:bands), which is closely tied to the STAC description of collections. I think it would be better to separate this from the essential cube metadata logic.

**Comment by soxofaan** [comment]
I think we should change it to:

- `CubeMetadata`: just the bare metadata essentials for a data cube: interface to interact with the cube dimensions and their labels (if available), maybe some resolution info too. Methods allow to construct a new `CubeMetadata` instance from an existing one (e.g. `reduce_dimension` eliminates a dimension)
- `CollectionMetadata` (subclass of `CubeMetadata`): interface to interact with all  original collection (STAC) metadata. Calling a "process" like `reduce_dimension` produces a `CubeMetadata`

By making `CollectionMetadata` a subclass of `CubeMetadata` we can stay backward compatible I think, because the interface of  `CollectionMetadata` would not really change

**Comment by jdries** [comment]
ok, makes sense!

**Comment by soxofaan** [comment]
Another reason for better abstraction: `load_stac` should produce a data cube with metadata (#425)  , but that is not the same as collection metadata.

**Comment by VictorVerhaert** [comment]
https://github.com/Open-EO/openeo-python-client/blob/498c4c7676f46d4ed6e858178cc08b1189a7699f/openeo/metadata.py#L231-L242
Currently functionality does not change due to this function.
As this function checks the type and returns an object of the same class, functions like `reduce_dimension` (who use this function to update a metadata object) will still return a CollectionMetadata object if that was the original object.

Changing this to return a CubeMetadata changes functionality and fails some existing tests.

An alternative is to provide an optional argument to set the expected returned class, however this feels more like a quick fix and might be confusing in the future.
