### ISSUE TITLE
Allow '_ensure_save_result' to be skipped with a flag in any place it is called.

### ISSUE THREAD

**Issue by GeraldIr** [Open-EO/openeo-python-client#513]
Often I find myself being unable to start jobs that have different result nodes which are incompatible with save_result and there has to be some workaround implemented for handling these edge cases.

I'd like to propose an optional flag for methods such as create_job and download which allows ensure save result to be skipped so that no superfluous save_result node gets added.

I can also create a PR for this if a change like this is approved.

**Comment by soxofaan** [comment]
is `save_ml_model` the only use case you're talking about? Because we can easily whitelist that process alongside `save_result` in the logic.

**Comment by ValentinaHutter** [comment]
I would like to skip the `save_result` for some of the `sen2like` processing and now created a PR to do so: https://github.com/Open-EO/openeo-python-client/pull/627 Not sure, if I miss something, I could not find a whitelist for `save_ml_model` to use it as an example.

**Comment by jdries** [comment]
Side note: if you do `connection.create_job(your_cube.flat_graph())`, no save_result will be added. This is the easy way around.
A better way forward would be to fetch the schema for the last process, and only add `save_result`if the output is a datacube.
Not the thing is, sen2like claims the output is a datacube, so as a user, I would expect that I actually need to add a `save_result`process, otherwise I won't get valid output. Also the process description does not mention anything in this regards.
@ValentinaHutter  Is that process metadata correct?

**Comment by ValentinaHutter** [comment]
Thanks for pointing this out, then I will use the create job with the flat graph for now! 
The reason for this is that sen2like processor natively generates a Sentinel2 like .SAFE folder holding all the results. In order to make use of other openeo processes on top of that, we then load the data from the .SAFE afterwards. So, when we only want to generate the .SAFE output, we would not need a save_result process afterwards. This is why the return value of sen2like is a datacube. This is described in the process metadata.

**Comment by soxofaan** [comment]
>  In order to make use of other openeo processes on top of that, we then load the data from the .SAFE afterwards.  So, when we only want to generate the .SAFE output, we would not need a save_result process afterwards.

I'm not completely following: if you don't have a save_result in your first job, you don't really have result assets in your job results so  how can you reference to that cube in another job? 

Isn't it better to define a "SAFE" file format in your capabilities to be used in this case?

**Comment by soxofaan** [comment]
added `auto_add_save_result` option to download/create_job/execute_batch with cfd9f1a91f15de9ba98b894dd7f038f656232fdc
