### ISSUE TITLE
pypi release for 0.4

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-python-client#68]
Could we get a pypi release for 0.4 once it is ready, please? This would allow us to use this library as a dependency for other projects, e.g. the backend-result-validator. See https://github.com/Open-EO/openeo-result-validation-engine/issues/43

**Comment by soxofaan** [comment]
Agree.

A couple of notes
- the python client version is currently `0.0.5`. Is there plan/intention to keep the openEO API versions in sync in some way with client versions (e.g. client version `x.y.z` is supposed to support openEO API up to at least `x.y.z`)? I'm not sure this is necessary or useful. On the contrary, this coupling could make things more complicated. 
- is there already a PyPI account for uploading/managing openEO related python packages on  PyPI?
- @jdries is on holiday till mid August since today, I am also two weeks away starting tomorrow, so it is not likely that this issue will be addressed quickly from the VITO side

**Comment by m-mohr** [comment]
> Is there plan/intention to keep the openEO API versions in sync in some way with client versions

No, not at all. For some libraries (Web Editor, JS, R) this is the case at the moment for minor versions (e.g. 0.4), but that's more a somewhat useful coincidence than a planned behaviour. So feel free to release it with whatever version you'd like, but according to the guidelines for the project, SemVer should be followed.

> * is there already a PyPI account for uploading/managing openEO related python packages on  PyPI?

I don't think there is an account yet as [there's no package yet](https://pypi.org/search/?q=openeo).

> * so it is not likely that this issue will be addressed quickly from the VITO side

Not a big deal, I think. We should release only once it's "ready" and I think the Python client needs some more work beforehand?

**Comment by soxofaan** [comment]
>  We should release only once it's "ready" and I think the Python client needs some more work beforehand?

Indeed, some more work is needed before it can be considered "ready".
On the other hand, we can already set up the necessary things: the client's version at the moment is only '0.0.5' which should indicate that it is not ready yet for broad consumption.

**Comment by m-mohr** [comment]
You could also release something like x.x.x-beta.1, which is what I do for the JS client, Web Editor etc.

**Comment by jdries** [comment]
Closing: multiple pypi releases have been published already, and we regularly create new releases.
