### ISSUE TITLE
oidc redirect as input param

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-python-client#94]
I am trying to use the oidc auth, but the redirect_uri is set in the python-client to be in the following form:
`http://localhost:3xxxx/callback`

This should be set by the user together with the client_id, since it is specific to the user's client_id.

(Should I open a separate issue for the following?)
When setting the redirect_uri manually in the code to the redirect_uri associated to my client_id, I could successfully log in, but then I received a "Unable to connect" message on my redirect. The same redirect works with Postman.

**Comment by soxofaan** [comment]
the redirect uri is served by a thread in the client process, so that the client process can extract the authorization code from the redirect. That's why it is currently set to localhost.
(There is a TODO item to change it to the fully qualified domain of the machine the client process is running on, but I have to test that a bit better).

Can you explain your context a bit more? To what do you want to change the redirect URI, and who/what will be serving that URI?

**Comment by lforesta** [comment]
The redirect_uri(s) is (are) set by a user when creating their client_id/client_secret on the Identity Provider supported by the openEO back-end they want to use.

So either we leave the redirect_uri as an input parameter (like the client_id), or we need to specify somewhere the specific redirect that the openEO client expects to find (e.g. for Python `http://localhost:5000/python-callback`

Either way, it can't be dynamically created by the client, else the user must map the redirect_uri to `*` to support this. Or am I missing something?

**Comment by soxofaan** [comment]
ok, I better understand what you refer to now.

There is indeed a bit of conflict
- for setting up an openeo client, you need a redirect URI, preferably with very limited wildcard usage  (otherwise it feels bad security-wise)
- in the context of the python client (e.g. jupyter session) the redirect URI is served by a short living side thread, which currently uses a "random" port (a port chosen by OS actually), which probably requires quite aggressive wildcard usage to get working properly

We could indeed let the user specify the redirect URI (or port number), but then it's the user's responsibility to make sure the URI properly resolves to the side thread server (or make sure the port is not occupied yet). Not very ideal or end-user friendly (especially because it is just for authentication).


The more that I work with it, the more I think that Resource Owner Password Credentials or Client Credentials Grant Types are more viable approaches (compared to the Authorization Code flow) to do authentication in practice for openEO

**Comment by lforesta** [comment]
I agree having to deal with the redirect_uri isn't user-friendly, but this seemd the only approach that would work with any openEO client during our OIDC call, no?

> The more that I work with it, the more I think that Resource Owner Password Credentials or Client Credentials Grant Types are more viable approaches (compared to the Authorization Code flow) to do authentication in practice for openEO

Here's an interesting article about the first of those two options:
[https://www.scottbrady91.com/OAuth/Why-the-Resource-Owner-Password-Credentials-Grant-Type-is-not-Authentication-nor-Suitable-for-Modern-Applications](https://www.scottbrady91.com/OAuth/Why-the-Resource-Owner-Password-Credentials-Grant-Type-is-not-Authentication-nor-Suitable-for-Modern-Applications)
It actually seems a plausible option for openEO clients which are "owned" by the user (e.g. the python client installed on one's laptop), but this is probably not the best option for the Web Editor or any "centralized" openEO client supporting multiple users on multiple back-ends.

It seems to me that we can't use one Grant type only, but different ones depending on the type of openEO client. This is also not user-friendly and confusing.

@soxofaan can you link again the doc you started writing before our OIDC call? I think we should document different options for the clients we have with their pros/cons (you did that already in that document maybe?)

**Comment by soxofaan** [comment]
indeed, my remark was probably to general/broad.

For traditional web clients like the web editor, it goes without saying to use the Authorization Code grant type.

Also for a (jupyter) notebook session running on your own laptop (meaning that something like "localhost:12345" resolves properly without issues), it is possible to get the Authorization Code grant type working.

But for other use cases (jupyter notebook on a remote server, command line scripts, batch/cron jobs without user interaction, ...) it will be cumbersome or impossible to do the Authorization Code flow.
In these cases however, it is probably safe to assume that the user indeed "owns" the source code, so using the password or client credentials grant types are feasible alternatives.

(FYI: yesterday I stumbled on the exact same article you linked there)

**Comment by soxofaan** [comment]
This can be closed I think: host name and port can be specified  (e.g. `server_address` arg of  `authenticate_oidc_authorization_code`).
Also the  auth code grant has lost importance for Python client usage now that device code grant is gaining popularity (also see #235 )
